# Generated by Django 5.2 on 2026-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_employeeprofile_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
