# Generated by Django 5.2 on 2026-04-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employeeprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
